general =
{
      name = "DAAK Mac Audio";
      service_type = "classic";
      output_backend = "ao";
      udp_port_base = 7211;
      udp_port_range = 10;
    interpolation = "soxr";
    ignore_volume_control = "no";
    default_airplay_volume = -18.0;
};

metadata =
{
    enabled = "yes";
    include_cover_art = "yes";
};
